CPP_QUESTIONS = [
    {
        "id": "cp001",
        "question": "Which operator is used to deallocate memory allocated with 'new' in C++?",
        "options": ["free", "delete", "remove", "destruct"],
        "answer": "delete",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp002",
        "question": "What is a virtual destructor in C++ used for?",
        "options": ["To destroy static objects", "To ensure base class destructor is called", "To ensure derived class destructor is called on deleting a base pointer", "To clear syntax errors"],
        "answer": "To ensure derived class destructor is called on deleting a base pointer",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp003",
        "question": "Which of the following is correct syntax to declare a pointer to a function in C++?",
        "options": ["void *ptr()", "void (*ptr)()", "void ptr*()", "void ptr()"],
        "answer": "void (*ptr)()",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp004",
        "question": "What is default access specifier for members of a class in C++?",
        "options": ["public", "protected", "private", "friend"],
        "answer": "private",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp005",
        "question": "What is the time complexity of lookup in std::unordered_map in C++?",
        "options": ["O(1) average", "O(log N)", "O(N)", "O(N log N)"],
        "answer": "O(1) average",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp006",
        "question": "Which keyword is used to declare a constant variable in C++?",
        "options": ["const", "constant", "final", "static"],
        "answer": "const",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp007",
        "question": "What is reference in C++?",
        "options": ["An alias for an existing variable", "A copy of a variable", "A pointer containing address", "A function call"],
        "answer": "An alias for an existing variable",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp008",
        "question": "What is a pure virtual function?",
        "options": ["A function with no return type", "A function declared with = 0 in base class", "A static class function", "A template function"],
        "answer": "A function declared with = 0 in base class",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp009",
        "question": "What is multiple inheritance in C++?",
        "options": ["A class inheriting from multiple classes", "A class inheriting from single parent", "A class with multiple instances", "Overloading constructor"],
        "answer": "A class inheriting from multiple classes",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp010",
        "question": "Which STL container is implemented as a self-balancing binary search tree?",
        "options": ["std::vector", "std::list", "std::set", "std::unordered_set"],
        "answer": "std::set",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "cp011",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q11)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp012",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q12)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp013",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q13)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp014",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q14)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp015",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q15)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp016",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q16)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp017",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q17)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp018",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q18)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Easy",
        "topic": "Pointers",
    },
    {
        "id": "cp019",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q19)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Medium",
        "topic": "Pointers",
    },
    {
        "id": "cp020",
        "question": "What is the output of pointer dereferencing dynamic memory in C++ (Q20)?",
        "options": ["Value stored in address", "Address itself", "Garbage value", "Null pointer exception"],
        "answer": "Value stored in address",
        "difficulty": "Medium",
        "topic": "Pointers",
    },
    {
        "id": "cp021",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q21)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp022",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q22)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp023",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q23)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp024",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q24)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp025",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q25)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp026",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q26)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp027",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q27)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp028",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q28)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp029",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q29)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp030",
        "question": "Which keyword is used to dynamically allocate memory on heap in C++ (Q30)?",
        "options": ["malloc", "calloc", "new", "alloc"],
        "answer": "new",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "cp031",
        "question": "How do you implement templates in C++ (Q31)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "Templates",
    },
    {
        "id": "cp032",
        "question": "How do you implement templates in C++ (Q32)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "Templates",
    },
    {
        "id": "cp033",
        "question": "How do you implement templates in C++ (Q33)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "Templates",
    },
    {
        "id": "cp034",
        "question": "How do you implement templates in C++ (Q34)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "Templates",
    },
    {
        "id": "cp035",
        "question": "How do you implement templates in C++ (Q35)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "Templates",
    },
    {
        "id": "cp036",
        "question": "How do you implement templates in C++ (Q36)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "Templates",
    },
    {
        "id": "cp037",
        "question": "How do you implement templates in C++ (Q37)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "Templates",
    },
    {
        "id": "cp038",
        "question": "How do you implement templates in C++ (Q38)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "Templates",
    },
    {
        "id": "cp039",
        "question": "How do you implement templates in C++ (Q39)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "Templates",
    },
    {
        "id": "cp040",
        "question": "How do you implement templates in C++ (Q40)?",
        "options": ["template <typename T>", "template <class T>", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "Templates",
    },
    {
        "id": "cp041",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q41)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp042",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q42)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp043",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q43)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp044",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q44)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp045",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q45)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp046",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q46)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp047",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q47)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp048",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q48)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp049",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q49)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp050",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q50)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
    {
        "id": "cp051",
        "question": "Which C++ STL container allows fast insertion/deletion at both ends (Q51)?",
        "options": ["std::vector", "std::deque", "std::list", "std::stack"],
        "answer": "std::deque",
        "difficulty": "Hard",
        "topic": "STL",
    },
]
