DATASCIENCE_QUESTIONS = [
    {
        "id": "ds001",
        "question": "What is overfitting in data science?",
        "options": ["Model performing poorly on training and testing data", "Model performing exceptionally well on training data but poorly on unseen test data", "Model training too fast", "Model using too many libraries"],
        "answer": "Model performing exceptionally well on training data but poorly on unseen test data",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds002",
        "question": "Which of the following is supervised learning algorithm?",
        "options": ["K-Means Clustering", "Linear Regression", "PCA (Principal Component Analysis)", "Apriori Algorithm"],
        "answer": "Linear Regression",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds003",
        "question": "What is purpose of imputation in data preprocessing?",
        "options": ["To delete outliers", "To fill in missing values in a dataset", "To normalize scales", "To split dataset 80/20"],
        "answer": "To fill in missing values in a dataset",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds004",
        "question": "What does PCA stand for in Data Science?",
        "options": ["Principal Component Analysis", "Pearson Correlation Accuracy", "Project Clustering Algorithm", "Python Data Compiler"],
        "answer": "Principal Component Analysis",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds005",
        "question": "What is the difference between Precision and Recall?",
        "options": ["Precision is true positives over predicted positives; Recall is true positives over actual positives", "Recall is true positives over predicted positives; Precision is actual positives", "They are identical", "Precision checks accuracy, Recall checks loss"],
        "answer": "Precision is true positives over predicted positives; Recall is true positives over actual positives",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds006",
        "question": "Which metric is best suited to evaluate regression models?",
        "options": ["F1-score", "Precision", "Mean Squared Error (MSE)", "ROC-AUC"],
        "answer": "Mean Squared Error (MSE)",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds007",
        "question": "What does the bias-variance tradeoff refer to?",
        "options": ["Increasing bias reduces variance, and vice versa; finding optimal balance is key to model generalization", "Trading hardware speed for database storage", "Using python vs R", "Splitting train and validation sets"],
        "answer": "Increasing bias reduces variance, and vice versa; finding optimal balance is key to model generalization",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds008",
        "question": "Which of the following is unsupervised clustering algorithm?",
        "options": ["Logistic Regression", "Support Vector Machine", "K-Means", "Random Forest"],
        "answer": "K-Means",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds009",
        "question": "What is a confusion matrix?",
        "options": ["A complex array structure", "A table used to describe performance of a classification model on test data with known true values", "A layout error in graphs", "A database relationship map"],
        "answer": "A table used to describe performance of a classification model on test data with known true values",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds010",
        "question": "What is the function of Pandas library in Python?",
        "options": ["To run neural networks", "To load data structures, manipulate, and analyze tabular data", "To plot histograms", "To build APIs"],
        "answer": "To load data structures, manipulate, and analyze tabular data",
        "difficulty": "Easy",
        "topic": "Data Prep",
    },
    {
        "id": "ds011",
        "question": "Which statistical value describes the middle point of a sorted data list (Q11)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds012",
        "question": "Which statistical value describes the middle point of a sorted data list (Q12)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds013",
        "question": "Which statistical value describes the middle point of a sorted data list (Q13)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds014",
        "question": "Which statistical value describes the middle point of a sorted data list (Q14)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds015",
        "question": "Which statistical value describes the middle point of a sorted data list (Q15)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds016",
        "question": "Which statistical value describes the middle point of a sorted data list (Q16)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds017",
        "question": "Which statistical value describes the middle point of a sorted data list (Q17)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds018",
        "question": "Which statistical value describes the middle point of a sorted data list (Q18)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Easy",
        "topic": "Statistics",
    },
    {
        "id": "ds019",
        "question": "Which statistical value describes the middle point of a sorted data list (Q19)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Medium",
        "topic": "Statistics",
    },
    {
        "id": "ds020",
        "question": "Which statistical value describes the middle point of a sorted data list (Q20)?",
        "options": ["Mean", "Median", "Mode", "Standard Deviation"],
        "answer": "Median",
        "difficulty": "Medium",
        "topic": "Statistics",
    },
    {
        "id": "ds021",
        "question": "What type of algorithm is Random Forest (Q21)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds022",
        "question": "What type of algorithm is Random Forest (Q22)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds023",
        "question": "What type of algorithm is Random Forest (Q23)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds024",
        "question": "What type of algorithm is Random Forest (Q24)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds025",
        "question": "What type of algorithm is Random Forest (Q25)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds026",
        "question": "What type of algorithm is Random Forest (Q26)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds027",
        "question": "What type of algorithm is Random Forest (Q27)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds028",
        "question": "What type of algorithm is Random Forest (Q28)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds029",
        "question": "What type of algorithm is Random Forest (Q29)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds030",
        "question": "What type of algorithm is Random Forest (Q30)?",
        "options": ["Ensemble Bagging Classifier/Regressor", "Boosting Algorithm", "Single Decision Tree", "Clustering algorithm"],
        "answer": "Ensemble Bagging Classifier/Regressor",
        "difficulty": "Medium",
        "topic": "Algorithms",
    },
    {
        "id": "ds031",
        "question": "What is cross-validation used for in machine learning (Q31)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Medium",
        "topic": "Model Tuning",
    },
    {
        "id": "ds032",
        "question": "What is cross-validation used for in machine learning (Q32)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Medium",
        "topic": "Model Tuning",
    },
    {
        "id": "ds033",
        "question": "What is cross-validation used for in machine learning (Q33)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Medium",
        "topic": "Model Tuning",
    },
    {
        "id": "ds034",
        "question": "What is cross-validation used for in machine learning (Q34)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Medium",
        "topic": "Model Tuning",
    },
    {
        "id": "ds035",
        "question": "What is cross-validation used for in machine learning (Q35)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Medium",
        "topic": "Model Tuning",
    },
    {
        "id": "ds036",
        "question": "What is cross-validation used for in machine learning (Q36)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Medium",
        "topic": "Model Tuning",
    },
    {
        "id": "ds037",
        "question": "What is cross-validation used for in machine learning (Q37)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Hard",
        "topic": "Model Tuning",
    },
    {
        "id": "ds038",
        "question": "What is cross-validation used for in machine learning (Q38)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Hard",
        "topic": "Model Tuning",
    },
    {
        "id": "ds039",
        "question": "What is cross-validation used for in machine learning (Q39)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Hard",
        "topic": "Model Tuning",
    },
    {
        "id": "ds040",
        "question": "What is cross-validation used for in machine learning (Q40)?",
        "options": ["To evaluate estimator performance by partitioning data into folds and testing iteratively", "To backup training weights", "To clean missing values", "To run multiple models parallel"],
        "answer": "To evaluate estimator performance by partitioning data into folds and testing iteratively",
        "difficulty": "Hard",
        "topic": "Model Tuning",
    },
    {
        "id": "ds041",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q41)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds042",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q42)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds043",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q43)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds044",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q44)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds045",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q45)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds046",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q46)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds047",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q47)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds048",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q48)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds049",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q49)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds050",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q50)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
    {
        "id": "ds051",
        "question": "Which chart is best suited to check correlation between two continuous numeric variables (Q51)?",
        "options": ["Histogram", "Bar chart", "Scatter Plot", "Pie Chart"],
        "answer": "Scatter Plot",
        "difficulty": "Hard",
        "topic": "Visualization",
    },
]
