DBMS_QUESTIONS = [
    {
        "id": "db001",
        "question": "What is a primary key in DBMS?",
        "options": ["A key that allows duplicate values", "A key that uniquely identifies each record in a table and cannot contain null", "A key linked to another table", "A static class identifier"],
        "answer": "A key that uniquely identifies each record in a table and cannot contain null",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db002",
        "question": "What does ACID stand for in DBMS?",
        "options": ["Atomicity, Consistency, Isolation, Durability", "Action, Coding, Integrity, Deployment", "Access, Control, Internal, Data", "Automated, Compiled, Integrated, Debugged"],
        "answer": "Atomicity, Consistency, Isolation, Durability",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db003",
        "question": "Which normal form removes partial dependencies?",
        "options": ["1NF", "2NF", "3NF", "BCNF"],
        "answer": "2NF",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db004",
        "question": "What is a foreign key?",
        "options": ["A field in one table that uniquely identifies a row of another table", "A duplicate key", "A primary key in same table", "A query search term"],
        "answer": "A field in one table that uniquely identifies a row of another table",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db005",
        "question": "Which normal form requires attributes to be atomic?",
        "options": ["1NF", "2NF", "3NF", "BCNF"],
        "answer": "1NF",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db006",
        "question": "What is the purpose of database indexing?",
        "options": ["To secure database records", "To speed up retrieval of data from table at the cost of slower writes", "To backup database files", "To design clean tables layout"],
        "answer": "To speed up retrieval of data from table at the cost of slower writes",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db007",
        "question": "What is a transaction in DBMS?",
        "options": ["A single logical unit of database work containing multiple operations", "A query execution statement", "An access logs file", "A network handshake"],
        "answer": "A single logical unit of database work containing multiple operations",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db008",
        "question": "Which normal form removes transitive dependencies?",
        "options": ["2NF", "3NF", "BCNF", "4NF"],
        "answer": "3NF",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db009",
        "question": "What is difference between DELETE and TRUNCATE commands?",
        "options": ["DELETE is DML and filters rows with WHERE; TRUNCATE is DDL and deletes all rows instantly without triggers", "TRUNCATE is DML, DELETE is DDL", "They are identical", "DELETE cannot be rolled back"],
        "answer": "DELETE is DML and filters rows with WHERE; TRUNCATE is DDL and deletes all rows instantly without triggers",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db010",
        "question": "What does DBMS stand for?",
        "options": ["Database Management System", "Data Block Management Structure", "Digital Business Monitor System", "Database Builder Module Software"],
        "answer": "Database Management System",
        "difficulty": "Easy",
        "topic": "Concepts",
    },
    {
        "id": "db011",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q11)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db012",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q12)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db013",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q13)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db014",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q14)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db015",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q15)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db016",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q16)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db017",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q17)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db018",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q18)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Easy",
        "topic": "SQL Basics",
    },
    {
        "id": "db019",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q19)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Medium",
        "topic": "SQL Basics",
    },
    {
        "id": "db020",
        "question": "Which SQL join returns all records when there is a match in either left or right table (Q20)?",
        "options": ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
        "answer": "FULL OUTER JOIN",
        "difficulty": "Medium",
        "topic": "SQL Basics",
    },
    {
        "id": "db021",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q21)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db022",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q22)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db023",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q23)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db024",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q24)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db025",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q25)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db026",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q26)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db027",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q27)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db028",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q28)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db029",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q29)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db030",
        "question": "What is Boyce-Codd Normal Form (BCNF) in DBMS (Q30)?",
        "options": ["An advanced normal form where every determinant must be a candidate key", "First level database cleanup", "A SQL indexing scheme", "An encryption algorithm"],
        "answer": "An advanced normal form where every determinant must be a candidate key",
        "difficulty": "Medium",
        "topic": "Normalization",
    },
    {
        "id": "db031",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q31)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Medium",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db032",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q32)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Medium",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db033",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q33)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Medium",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db034",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q34)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Medium",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db035",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q35)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Medium",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db036",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q36)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Medium",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db037",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q37)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Hard",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db038",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q38)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Hard",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db039",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q39)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Hard",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db040",
        "question": "Which ACID property guarantees that a transaction once committed remains safe even in case of system failure (Q40)?",
        "options": ["Atomicity", "Consistency", "Isolation", "Durability"],
        "answer": "Durability",
        "difficulty": "Hard",
        "topic": "Transactions & ACID",
    },
    {
        "id": "db041",
        "question": "What is a clustered index in DBMS (Q41)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db042",
        "question": "What is a clustered index in DBMS (Q42)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db043",
        "question": "What is a clustered index in DBMS (Q43)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db044",
        "question": "What is a clustered index in DBMS (Q44)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db045",
        "question": "What is a clustered index in DBMS (Q45)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db046",
        "question": "What is a clustered index in DBMS (Q46)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db047",
        "question": "What is a clustered index in DBMS (Q47)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db048",
        "question": "What is a clustered index in DBMS (Q48)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db049",
        "question": "What is a clustered index in DBMS (Q49)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db050",
        "question": "What is a clustered index in DBMS (Q50)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
    {
        "id": "db051",
        "question": "What is a clustered index in DBMS (Q51)?",
        "options": ["An index that defines the physical order of data storage in table", "An index containing multiple columns", "A security encryption key", "A backup partition"],
        "answer": "An index that defines the physical order of data storage in table",
        "difficulty": "Hard",
        "topic": "Indexing",
    },
]
