JAVA_QUESTIONS = [
    {
        "id": "jv001",
        "question": "Which of the following is not a primitive data type in Java?",
        "options": ["int", "double", "boolean", "String"],
        "answer": "String",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv002",
        "question": "What is the default value of a local variable in Java?",
        "options": ["0", "null", "No default value (Compiler error)", "Depends on the type"],
        "answer": "No default value (Compiler error)",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv003",
        "question": "Which keyword is used to inherit a class in Java?",
        "options": ["implements", "extends", "inherits", "import"],
        "answer": "extends",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv004",
        "question": "What is the size of 'char' data type in Java?",
        "options": ["8-bit", "16-bit", "32-bit", "Depends on OS"],
        "answer": "16-bit",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv005",
        "question": "Which class is the superclass of all classes in Java?",
        "options": ["Class", "Object", "System", "Main"],
        "answer": "Object",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv006",
        "question": "Which method is used to start a thread in Java?",
        "options": ["run()", "start()", "init()", "execute()"],
        "answer": "start()",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv007",
        "question": "What is bytecode in the context of Java?",
        "options": ["Machine code", "High-level Java source code", "Compiled representation of Java code for JVM", "Assembler code"],
        "answer": "Compiled representation of Java code for JVM",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv008",
        "question": "Which of the following creates a thread-safe list in Java?",
        "options": ["ArrayList", "Vector", "LinkedList", "HashSet"],
        "answer": "Vector",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv009",
        "question": "Which keyword makes a variable or method belong to a class rather than an instance?",
        "options": ["static", "final", "abstract", "volatile"],
        "answer": "static",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv010",
        "question": "What does the JVM stand for?",
        "options": ["Java Virtual Machine", "Java Variable Manager", "Java Visual Monitor", "Java Vector Module"],
        "answer": "Java Virtual Machine",
        "difficulty": "Easy",
        "topic": "Syntax",
    },
    {
        "id": "jv011",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q11)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv012",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q12)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv013",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q13)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv014",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q14)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv015",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q15)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv016",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q16)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv017",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q17)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv018",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q18)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Easy",
        "topic": "OOP",
    },
    {
        "id": "jv019",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q19)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "jv020",
        "question": "Which of the following OOP concept is demonstrated by method overloading in Java (Q20)?",
        "options": ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
        "answer": "Polymorphism",
        "difficulty": "Medium",
        "topic": "OOP",
    },
    {
        "id": "jv021",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q21)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv022",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q22)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv023",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q23)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv024",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q24)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv025",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q25)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv026",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q26)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv027",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q27)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv028",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q28)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv029",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q29)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv030",
        "question": "Which collection implementation is backed by a double-linked list in Java (Q30)?",
        "options": ["ArrayList", "LinkedList", "Vector", "Stack"],
        "answer": "LinkedList",
        "difficulty": "Medium",
        "topic": "Collections",
    },
    {
        "id": "jv031",
        "question": "Which interface should be implemented to define a task run by a thread (Q31)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Medium",
        "topic": "Concurrency",
    },
    {
        "id": "jv032",
        "question": "Which interface should be implemented to define a task run by a thread (Q32)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Medium",
        "topic": "Concurrency",
    },
    {
        "id": "jv033",
        "question": "Which interface should be implemented to define a task run by a thread (Q33)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Medium",
        "topic": "Concurrency",
    },
    {
        "id": "jv034",
        "question": "Which interface should be implemented to define a task run by a thread (Q34)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Medium",
        "topic": "Concurrency",
    },
    {
        "id": "jv035",
        "question": "Which interface should be implemented to define a task run by a thread (Q35)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Medium",
        "topic": "Concurrency",
    },
    {
        "id": "jv036",
        "question": "Which interface should be implemented to define a task run by a thread (Q36)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Medium",
        "topic": "Concurrency",
    },
    {
        "id": "jv037",
        "question": "Which interface should be implemented to define a task run by a thread (Q37)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Hard",
        "topic": "Concurrency",
    },
    {
        "id": "jv038",
        "question": "Which interface should be implemented to define a task run by a thread (Q38)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Hard",
        "topic": "Concurrency",
    },
    {
        "id": "jv039",
        "question": "Which interface should be implemented to define a task run by a thread (Q39)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Hard",
        "topic": "Concurrency",
    },
    {
        "id": "jv040",
        "question": "Which interface should be implemented to define a task run by a thread (Q40)?",
        "options": ["Runnable", "Thread", "Callable", "Executor"],
        "answer": "Runnable",
        "difficulty": "Hard",
        "topic": "Concurrency",
    },
    {
        "id": "jv041",
        "question": "What is the function of the Java Garbage Collector (Q41)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv042",
        "question": "What is the function of the Java Garbage Collector (Q42)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv043",
        "question": "What is the function of the Java Garbage Collector (Q43)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv044",
        "question": "What is the function of the Java Garbage Collector (Q44)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv045",
        "question": "What is the function of the Java Garbage Collector (Q45)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv046",
        "question": "What is the function of the Java Garbage Collector (Q46)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv047",
        "question": "What is the function of the Java Garbage Collector (Q47)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv048",
        "question": "What is the function of the Java Garbage Collector (Q48)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv049",
        "question": "What is the function of the Java Garbage Collector (Q49)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv050",
        "question": "What is the function of the Java Garbage Collector (Q50)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
    {
        "id": "jv051",
        "question": "What is the function of the Java Garbage Collector (Q51)?",
        "options": ["Reclaims unused memory automatically", "Destroys objects when they go out of scope", "Cleans syntax errors", "Optimizes JVM bytecode"],
        "answer": "Reclaims unused memory automatically",
        "difficulty": "Hard",
        "topic": "JVM",
    },
]
