JS_QUESTIONS = [
    {
        "id": "js001",
        "question": "What is the output of: console.log(typeof null) in JavaScript?",
        "options": ["'null'", "'undefined'", "'object'", "'string'"],
        "answer": "'object'",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js002",
        "question": "Which of the following is used to declare block-scoped variables in JS?",
        "options": ["var", "let", "const", "Both let and const"],
        "answer": "Both let and const",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js003",
        "question": "What is a closure in JavaScript?",
        "options": ["A way to close a database", "A function that has access to its outer function scope even after outer function has returned", "A CSS styling rule", "A script loader"],
        "answer": "A function that has access to its outer function scope even after outer function has returned",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js004",
        "question": "What is the difference between '==' and '===' operators in JS?",
        "options": ["'==' checks value only, '===' checks value and type", "'===' checks value only, '==' checks value and type", "They are identical", "'==' is faster"],
        "answer": "'==' checks value only, '===' checks value and type",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js005",
        "question": "Which method is used to parse a JSON string into an object?",
        "options": ["JSON.stringify()", "JSON.parse()", "JSON.objectify()", "JSON.decode()"],
        "answer": "JSON.parse()",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js006",
        "question": "What is event bubbling in JavaScript?",
        "options": ["Event moves from target element up to parent elements", "Event moves from parent down to target element", "Creating elements dynamically", "An error handling method"],
        "answer": "Event moves from target element up to parent elements",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js007",
        "question": "What does 'NaN' stand for in JS?",
        "options": ["Null And None", "Not a Number", "New Array Node", "Not a Null"],
        "answer": "Not a Number",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js008",
        "question": "What is the output of: console.log(1 + '2')?",
        "options": ["3", "12", "NaN", "TypeError"],
        "answer": "12",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js009",
        "question": "How do you create a promise in JavaScript?",
        "options": ["new Promise((resolve, reject) => {})", "Promise.create()", "Promise.new()", "new Promise()"],
        "answer": "new Promise((resolve, reject) => {})",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js010",
        "question": "Which keyword is used to handle asynchronous operations in a synchronous fashion?",
        "options": ["async/await", "then/catch", "promise", "defer"],
        "answer": "async/await",
        "difficulty": "Easy",
        "topic": "Basics",
    },
    {
        "id": "js011",
        "question": "What is hoisting in JavaScript (Q11)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js012",
        "question": "What is hoisting in JavaScript (Q12)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js013",
        "question": "What is hoisting in JavaScript (Q13)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js014",
        "question": "What is hoisting in JavaScript (Q14)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js015",
        "question": "What is hoisting in JavaScript (Q15)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js016",
        "question": "What is hoisting in JavaScript (Q16)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js017",
        "question": "What is hoisting in JavaScript (Q17)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js018",
        "question": "What is hoisting in JavaScript (Q18)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Easy",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js019",
        "question": "What is hoisting in JavaScript (Q19)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Medium",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js020",
        "question": "What is hoisting in JavaScript (Q20)?",
        "options": ["Variables and functions declarations are moved to the top of their scope before code execution", "Loading scripts asynchronously", "Sorting arrays", "Compressing code size"],
        "answer": "Variables and functions declarations are moved to the top of their scope before code execution",
        "difficulty": "Medium",
        "topic": "Scopes & Closures",
    },
    {
        "id": "js021",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q21)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js022",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q22)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js023",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q23)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js024",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q24)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js025",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q25)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js026",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q26)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js027",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q27)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js028",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q28)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js029",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q29)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js030",
        "question": "Which built-in JS method executes a function repeatedly after a set interval (Q30)?",
        "options": ["setTimeout", "setInterval", "setDelay", "runInterval"],
        "answer": "setInterval",
        "difficulty": "Medium",
        "topic": "Promises & Async",
    },
    {
        "id": "js031",
        "question": "How do you select an element by its ID in JavaScript (Q31)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "DOM",
    },
    {
        "id": "js032",
        "question": "How do you select an element by its ID in JavaScript (Q32)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "DOM",
    },
    {
        "id": "js033",
        "question": "How do you select an element by its ID in JavaScript (Q33)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "DOM",
    },
    {
        "id": "js034",
        "question": "How do you select an element by its ID in JavaScript (Q34)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "DOM",
    },
    {
        "id": "js035",
        "question": "How do you select an element by its ID in JavaScript (Q35)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "DOM",
    },
    {
        "id": "js036",
        "question": "How do you select an element by its ID in JavaScript (Q36)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Medium",
        "topic": "DOM",
    },
    {
        "id": "js037",
        "question": "How do you select an element by its ID in JavaScript (Q37)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "DOM",
    },
    {
        "id": "js038",
        "question": "How do you select an element by its ID in JavaScript (Q38)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "DOM",
    },
    {
        "id": "js039",
        "question": "How do you select an element by its ID in JavaScript (Q39)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "DOM",
    },
    {
        "id": "js040",
        "question": "How do you select an element by its ID in JavaScript (Q40)?",
        "options": ["document.getElementById()", "document.querySelector()", "Both of the above", "None of the above"],
        "answer": "Both of the above",
        "difficulty": "Hard",
        "topic": "DOM",
    },
    {
        "id": "js041",
        "question": "What is a Generator function in JS (Q41)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js042",
        "question": "What is a Generator function in JS (Q42)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js043",
        "question": "What is a Generator function in JS (Q43)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js044",
        "question": "What is a Generator function in JS (Q44)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js045",
        "question": "What is a Generator function in JS (Q45)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js046",
        "question": "What is a Generator function in JS (Q46)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js047",
        "question": "What is a Generator function in JS (Q47)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js048",
        "question": "What is a Generator function in JS (Q48)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js049",
        "question": "What is a Generator function in JS (Q49)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js050",
        "question": "What is a Generator function in JS (Q50)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
    {
        "id": "js051",
        "question": "What is a Generator function in JS (Q51)?",
        "options": ["A function that can yield execution flow and resume later", "A function that generates random numbers", "A class definition constructor", "An API builder"],
        "answer": "A function that can yield execution flow and resume later",
        "difficulty": "Hard",
        "topic": "Advanced JS",
    },
]
