NETWORKS_QUESTIONS = [
    {
        "id": "nt001",
        "question": "How many layers are in OSI model?",
        "options": ["4", "5", "7", "8"],
        "answer": "7",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt002",
        "question": "Which protocol is connection-oriented?",
        "options": ["UDP", "TCP", "IP", "DNS"],
        "answer": "TCP",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt003",
        "question": "What is DNS in computer networks?",
        "options": ["Data Network System", "Domain Name System", "Digital Node Server", "Domain Node Service"],
        "answer": "Domain Name System",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt004",
        "question": "Which layer of OSI model is responsible for routing?",
        "options": ["Physical Layer", "Data Link Layer", "Network Layer", "Transport Layer"],
        "answer": "Network Layer",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt005",
        "question": "What is subnetting in networks?",
        "options": ["Dividing a physical network into smaller logical subnetworks", "Hosting websites", "Creating proxy paths", "Routing DNS queries"],
        "answer": "Dividing a physical network into smaller logical subnetworks",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt006",
        "question": "Which layer of OSI model performs encryption/decryption?",
        "options": ["Application Layer", "Presentation Layer", "Session Layer", "Transport Layer"],
        "answer": "Presentation Layer",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt007",
        "question": "What is DHCP protocol used for?",
        "options": ["To route packets", "To dynamically assign IP addresses to devices on a network", "To secure web connections", "To resolve domain names"],
        "answer": "To dynamically assign IP addresses to devices on a network",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt008",
        "question": "What is difference between TCP and UDP?",
        "options": ["TCP is connection-oriented and reliable, UDP is connectionless and fast", "UDP is connection-oriented, TCP is connectionless", "They are identical", "TCP is faster than UDP"],
        "answer": "TCP is connection-oriented and reliable, UDP is connectionless and fast",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt009",
        "question": "What is the standard port number for HTTPS?",
        "options": ["80", "8080", "443", "22"],
        "answer": "443",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt010",
        "question": "What is NAT in networks?",
        "options": ["Network Address Translation", "Node Access Technology", "Digital Adapter Tool", "Network Area Topology"],
        "answer": "Network Address Translation",
        "difficulty": "Easy",
        "topic": "OSI Model",
    },
    {
        "id": "nt011",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q11)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt012",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q12)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt013",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q13)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt014",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q14)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt015",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q15)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt016",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q16)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt017",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q17)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt018",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q18)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Easy",
        "topic": "TCP/IP",
    },
    {
        "id": "nt019",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q19)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Medium",
        "topic": "TCP/IP",
    },
    {
        "id": "nt020",
        "question": "Which layer of TCP/IP model corresponds to OSI Network layer (Q20)?",
        "options": ["Internet Layer", "Network Access Layer", "Application Layer", "Transport Layer"],
        "answer": "Internet Layer",
        "difficulty": "Medium",
        "topic": "TCP/IP",
    },
    {
        "id": "nt021",
        "question": "Which routing protocol is based on link-state algorithm (Q21)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt022",
        "question": "Which routing protocol is based on link-state algorithm (Q22)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt023",
        "question": "Which routing protocol is based on link-state algorithm (Q23)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt024",
        "question": "Which routing protocol is based on link-state algorithm (Q24)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt025",
        "question": "Which routing protocol is based on link-state algorithm (Q25)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt026",
        "question": "Which routing protocol is based on link-state algorithm (Q26)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt027",
        "question": "Which routing protocol is based on link-state algorithm (Q27)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt028",
        "question": "Which routing protocol is based on link-state algorithm (Q28)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt029",
        "question": "Which routing protocol is based on link-state algorithm (Q29)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt030",
        "question": "Which routing protocol is based on link-state algorithm (Q30)?",
        "options": ["RIP", "OSPF", "BGP", "EIGRP"],
        "answer": "OSPF",
        "difficulty": "Medium",
        "topic": "Protocols",
    },
    {
        "id": "nt031",
        "question": "What is 3-way handshake in TCP (Q31)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "nt032",
        "question": "What is 3-way handshake in TCP (Q32)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "nt033",
        "question": "What is 3-way handshake in TCP (Q33)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "nt034",
        "question": "What is 3-way handshake in TCP (Q34)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "nt035",
        "question": "What is 3-way handshake in TCP (Q35)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "nt036",
        "question": "What is 3-way handshake in TCP (Q36)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "nt037",
        "question": "What is 3-way handshake in TCP (Q37)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "nt038",
        "question": "What is 3-way handshake in TCP (Q38)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "nt039",
        "question": "What is 3-way handshake in TCP (Q39)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "nt040",
        "question": "What is 3-way handshake in TCP (Q40)?",
        "options": ["SYN -> SYN-ACK -> ACK", "SYN -> ACK -> FIN", "Hello -> Request -> Response", "Ping -> Pong -> Ack"],
        "answer": "SYN -> SYN-ACK -> ACK",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "nt041",
        "question": "What does symmetric encryption mean in computer network security (Q41)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt042",
        "question": "What does symmetric encryption mean in computer network security (Q42)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt043",
        "question": "What does symmetric encryption mean in computer network security (Q43)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt044",
        "question": "What does symmetric encryption mean in computer network security (Q44)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt045",
        "question": "What does symmetric encryption mean in computer network security (Q45)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt046",
        "question": "What does symmetric encryption mean in computer network security (Q46)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt047",
        "question": "What does symmetric encryption mean in computer network security (Q47)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt048",
        "question": "What does symmetric encryption mean in computer network security (Q48)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt049",
        "question": "What does symmetric encryption mean in computer network security (Q49)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt050",
        "question": "What does symmetric encryption mean in computer network security (Q50)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
    {
        "id": "nt051",
        "question": "What does symmetric encryption mean in computer network security (Q51)?",
        "options": ["Same key used for encryption and decryption", "Different keys used", "Cloud based authentication", "DNS security filtering"],
        "answer": "Same key used for encryption and decryption",
        "difficulty": "Hard",
        "topic": "Security",
    },
]
