OS_QUESTIONS = [
    {
        "id": "os001",
        "question": "What is a process in OS?",
        "options": ["A program in execution", "A text file on disk", "A hardware interface", "A compiled module"],
        "answer": "A program in execution",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os002",
        "question": "What is a deadlock in OS?",
        "options": ["A process crash", "A situation where set of processes are blocked because each process is holding a resource and waiting for another process", "A system bootup lock", "An infinite loop"],
        "answer": "A situation where set of processes are blocked because each process is holding a resource and waiting for another process",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os003",
        "question": "What is virtual memory in OS?",
        "options": ["Extra RAM chip", "A memory management capability of OS using disk space to extend RAM capacity virtualizing physical memory", "A cloud server space", "An emulator RAM partition"],
        "answer": "A memory management capability of OS using disk space to extend RAM capacity virtualizing physical memory",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os004",
        "question": "What is context switching?",
        "options": ["Switching between dark and light UI theme", "Saving state of an active process and loading state of next process to run", "Rebooting computer", "Exchanging file paths"],
        "answer": "Saving state of an active process and loading state of next process to run",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os005",
        "question": "Which CPU scheduling algorithm is non-preemptive by definition?",
        "options": ["Round Robin", "First-Come First-Served (FCFS)", "Shortest Remaining Time First", "Priority Scheduling (preemptive version)"],
        "answer": "First-Come First-Served (FCFS)",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os006",
        "question": "What is paging in OS?",
        "options": ["Dividing logical memory into fixed-size blocks called pages", "A web development technique", "Cleaning disk sectors", "Sorting files dynamically"],
        "answer": "Dividing logical memory into fixed-size blocks called pages",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os007",
        "question": "What is thrashing in OS?",
        "options": ["High CPU utilization", "A state where CPU spends more time swapping pages in and out of disk than executing processes", "A virus attack", "Defragmenting files"],
        "answer": "A state where CPU spends more time swapping pages in and out of disk than executing processes",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os008",
        "question": "What are necessary conditions for deadlock?",
        "options": ["Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait", "Starvation, Race Condition, Synchronization", "Paging, Fragmentation, Swapping", "Semaphore, Mutex, Monitor"],
        "answer": "Mutual Exclusion, Hold and Wait, No Preemption, Circular Wait",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os009",
        "question": "What is a semaphore in OS?",
        "options": ["A graphical UI tool", "An integer variable used to solve critical section problem in process synchronization", "A hardware adapter", "A file system format"],
        "answer": "An integer variable used to solve critical section problem in process synchronization",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os010",
        "question": "What is a kernel in OS?",
        "options": ["The core component of OS that manages system resources and CPU-hardware communications", "A text compiler", "A device driver software", "A virus scanner tool"],
        "answer": "The core component of OS that manages system resources and CPU-hardware communications",
        "difficulty": "Easy",
        "topic": "Process",
    },
    {
        "id": "os011",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q11)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os012",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q12)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os013",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q13)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os014",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q14)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os015",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q15)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os016",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q16)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os017",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q17)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os018",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q18)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Easy",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os019",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q19)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Medium",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os020",
        "question": "Which CPU scheduling algorithm gives smallest average waiting time for set of processes (Q20)?",
        "options": ["SJF (Shortest Job First)", "FCFS", "Round Robin", "Priority"],
        "answer": "SJF (Shortest Job First)",
        "difficulty": "Medium",
        "topic": "CPU Scheduling",
    },
    {
        "id": "os021",
        "question": "What is internal fragmentation (Q21)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os022",
        "question": "What is internal fragmentation (Q22)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os023",
        "question": "What is internal fragmentation (Q23)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os024",
        "question": "What is internal fragmentation (Q24)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os025",
        "question": "What is internal fragmentation (Q25)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os026",
        "question": "What is internal fragmentation (Q26)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os027",
        "question": "What is internal fragmentation (Q27)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os028",
        "question": "What is internal fragmentation (Q28)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os029",
        "question": "What is internal fragmentation (Q29)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os030",
        "question": "What is internal fragmentation (Q30)?",
        "options": ["Wasted memory inside allocated block size", "Wasted memory between allocated segments", "Files scattered on disk sectors", "A hard drive failure"],
        "answer": "Wasted memory inside allocated block size",
        "difficulty": "Medium",
        "topic": "Memory Management",
    },
    {
        "id": "os031",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q31)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Medium",
        "topic": "Deadlocks",
    },
    {
        "id": "os032",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q32)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Medium",
        "topic": "Deadlocks",
    },
    {
        "id": "os033",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q33)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Medium",
        "topic": "Deadlocks",
    },
    {
        "id": "os034",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q34)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Medium",
        "topic": "Deadlocks",
    },
    {
        "id": "os035",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q35)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Medium",
        "topic": "Deadlocks",
    },
    {
        "id": "os036",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q36)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Medium",
        "topic": "Deadlocks",
    },
    {
        "id": "os037",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q37)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Hard",
        "topic": "Deadlocks",
    },
    {
        "id": "os038",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q38)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Hard",
        "topic": "Deadlocks",
    },
    {
        "id": "os039",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q39)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Hard",
        "topic": "Deadlocks",
    },
    {
        "id": "os040",
        "question": "Which method is used to avoid deadlocks by dynamically checking resource allocation state (Q40)?",
        "options": ["Banker's Algorithm", "Round Robin Scheduling", "Paging allocation", "LRU Page replacement"],
        "answer": "Banker's Algorithm",
        "difficulty": "Hard",
        "topic": "Deadlocks",
    },
    {
        "id": "os041",
        "question": "What is a virtual file system (VFS) in OS (Q41)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os042",
        "question": "What is a virtual file system (VFS) in OS (Q42)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os043",
        "question": "What is a virtual file system (VFS) in OS (Q43)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os044",
        "question": "What is a virtual file system (VFS) in OS (Q44)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os045",
        "question": "What is a virtual file system (VFS) in OS (Q45)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os046",
        "question": "What is a virtual file system (VFS) in OS (Q46)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os047",
        "question": "What is a virtual file system (VFS) in OS (Q47)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os048",
        "question": "What is a virtual file system (VFS) in OS (Q48)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os049",
        "question": "What is a virtual file system (VFS) in OS (Q49)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os050",
        "question": "What is a virtual file system (VFS) in OS (Q50)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
    {
        "id": "os051",
        "question": "What is a virtual file system (VFS) in OS (Q51)?",
        "options": ["An abstraction layer allowing OS to access different physical file systems under unified API", "A backup system on cloud", "A network storage protocol", "A folder manager emulated"],
        "answer": "An abstraction layer allowing OS to access different physical file systems under unified API",
        "difficulty": "Hard",
        "topic": "File System",
    },
]
