REACT_QUESTIONS = [
    {
        "id": "re001",
        "question": "What is JSX in React?",
        "options": ["A database wrapper", "A syntax extension that allows writing HTML tags inside JavaScript", "A styling format", "A deployment tool"],
        "answer": "A syntax extension that allows writing HTML tags inside JavaScript",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re002",
        "question": "Which Hook is used to perform side effects in React functional components?",
        "options": ["useState", "useEffect", "useReducer", "useContext"],
        "answer": "useEffect",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re003",
        "question": "What is virtual DOM in React?",
        "options": ["A direct copy of browser DOM", "A lightweight, in-memory representation of real DOM elements", "A cloud-hosted HTML framework", "A routing engine"],
        "answer": "A lightweight, in-memory representation of real DOM elements",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re004",
        "question": "How do you pass data from a parent component to child component?",
        "options": ["Using state", "Using props", "Using context", "Using Redux"],
        "answer": "Using props",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re005",
        "question": "Which hook is used to access the React context directly?",
        "options": ["useContext", "useState", "useRef", "useMemo"],
        "answer": "useContext",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re006",
        "question": "What is the purpose of 'key' prop in React lists?",
        "options": ["To style list elements", "To help React identify which items have changed, been added, or removed", "To count the number of elements", "To secure component state"],
        "answer": "To help React identify which items have changed, been added, or removed",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re007",
        "question": "Which Hook returns a mutable ref object whose .current property is initialized to passed argument?",
        "options": ["useMemo", "useRef", "useCallback", "useState"],
        "answer": "useRef",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re008",
        "question": "What is React.memo used for?",
        "options": ["To store local state", "To memoize functional components, preventing unnecessary re-renders when props don't change", "To handle network requests", "To build forms"],
        "answer": "To memoize functional components, preventing unnecessary re-renders when props don't change",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re009",
        "question": "What are custom Hooks in React?",
        "options": ["Styled elements", "JavaScript functions that start with 'use' and can call other Hooks", "Global state managers", "Custom React components"],
        "answer": "JavaScript functions that start with 'use' and can call other Hooks",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re010",
        "question": "Which method in React router is used to navigate programmatically?",
        "options": ["useNavigate()", "Link component", "useHistory()", "Both useNavigate() and useHistory() depending on v5 vs v6"],
        "answer": "Both useNavigate() and useHistory() depending on v5 vs v6",
        "difficulty": "Easy",
        "topic": "Components",
    },
    {
        "id": "re011",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q11)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re012",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q12)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re013",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q13)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re014",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q14)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re015",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q15)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re016",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q16)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re017",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q17)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re018",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q18)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Easy",
        "topic": "Hooks",
    },
    {
        "id": "re019",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q19)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Medium",
        "topic": "Hooks",
    },
    {
        "id": "re020",
        "question": "Which hook is used to optimize performance by memoizing complex calculations (Q20)?",
        "options": ["useMemo", "useCallback", "useEffect", "useReducer"],
        "answer": "useMemo",
        "difficulty": "Medium",
        "topic": "Hooks",
    },
    {
        "id": "re021",
        "question": "What is Redux in context of React (Q21)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re022",
        "question": "What is Redux in context of React (Q22)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re023",
        "question": "What is Redux in context of React (Q23)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re024",
        "question": "What is Redux in context of React (Q24)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re025",
        "question": "What is Redux in context of React (Q25)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re026",
        "question": "What is Redux in context of React (Q26)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re027",
        "question": "What is Redux in context of React (Q27)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re028",
        "question": "What is Redux in context of React (Q28)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re029",
        "question": "What is Redux in context of React (Q29)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re030",
        "question": "What is Redux in context of React (Q30)?",
        "options": ["A global state management library", "A local styling plugin", "A routing module", "A virtual DOM emulator"],
        "answer": "A global state management library",
        "difficulty": "Medium",
        "topic": "State Management",
    },
    {
        "id": "re031",
        "question": "Which element is used to render child routes in React Router v6 (Q31)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "re032",
        "question": "Which element is used to render child routes in React Router v6 (Q32)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "re033",
        "question": "Which element is used to render child routes in React Router v6 (Q33)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "re034",
        "question": "Which element is used to render child routes in React Router v6 (Q34)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "re035",
        "question": "Which element is used to render child routes in React Router v6 (Q35)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "re036",
        "question": "Which element is used to render child routes in React Router v6 (Q36)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Medium",
        "topic": "Routing",
    },
    {
        "id": "re037",
        "question": "Which element is used to render child routes in React Router v6 (Q37)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "re038",
        "question": "Which element is used to render child routes in React Router v6 (Q38)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "re039",
        "question": "Which element is used to render child routes in React Router v6 (Q39)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "re040",
        "question": "Which element is used to render child routes in React Router v6 (Q40)?",
        "options": ["<Outlet />", "<Route />", "<Children />", "<Switch />"],
        "answer": "<Outlet />",
        "difficulty": "Hard",
        "topic": "Routing",
    },
    {
        "id": "re041",
        "question": "What does standard React hydration mean (Q41)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re042",
        "question": "What does standard React hydration mean (Q42)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re043",
        "question": "What does standard React hydration mean (Q43)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re044",
        "question": "What does standard React hydration mean (Q44)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re045",
        "question": "What does standard React hydration mean (Q45)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re046",
        "question": "What does standard React hydration mean (Q46)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re047",
        "question": "What does standard React hydration mean (Q47)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re048",
        "question": "What does standard React hydration mean (Q48)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re049",
        "question": "What does standard React hydration mean (Q49)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re050",
        "question": "What does standard React hydration mean (Q50)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
    {
        "id": "re051",
        "question": "What does standard React hydration mean (Q51)?",
        "options": ["Attaching event listeners to HTML pre-rendered on server", "Adding CSS to styling files", "Executing API calls in database", "Refreshing virtual DOM"],
        "answer": "Attaching event listeners to HTML pre-rendered on server",
        "difficulty": "Hard",
        "topic": "Advanced React",
    },
]
