REASONING_QUESTIONS = [
    {
        "id": "rs001",
        "question": "Find the missing term: 2, 6, 12, 20, 30, ?",
        "options": ["36", "40", "42", "48"],
        "answer": "42",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs002",
        "question": "Pointing to a photograph, a man said, 'I have no brother or sister but that man's father is my father's son.' Whose photograph was it?",
        "options": ["His own", "His son's", "His father's", "His nephew's"],
        "answer": "His son's",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs003",
        "question": "If in a certain language, CHARCOAL is coded as 45162913, how is COAL coded?",
        "options": ["4913", "4213", "4513", "4613"],
        "answer": "4213",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs004",
        "question": "Statements: All poets are day-dreamers. All painters are day-dreamers. Conclusions: I. All poets are painters. II. Some day-dreamers are not painters.",
        "options": ["Only I follows", "Only II follows", "Either I or II follows", "Neither I nor II follows"],
        "answer": "Neither I nor II follows",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs005",
        "question": "A man walks 5 km toward South and then turns to the right. After walking 3 km he turns to the left and walks 5 km. Now in which direction is he from the starting place?",
        "options": ["West", "South", "South-West", "North-East"],
        "answer": "South-West",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs006",
        "question": "Find missing number: 3, 5, 9, 17, 33, ?",
        "options": ["65", "60", "50", "45"],
        "answer": "65",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs007",
        "question": "If A is B's sister, C is B's mother, D is C's father, E is D's mother. How is A related to D?",
        "options": ["Grandmother", "Grandfather", "Granddaughter", "Daughter"],
        "answer": "Granddaughter",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs008",
        "question": "If 'ROSE' is coded as 'TQUG', how is 'BISCUIT' coded?",
        "options": ["DKUEWKV", "DKVEXJW", "DKUEWKY", "CJTFVJU"],
        "answer": "DKUEWKV",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs009",
        "question": "Statements: Some papers are pens. All pencils are pens. Conclusions: I. Some pens are pencils. II. Some pens are papers.",
        "options": ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"],
        "answer": "Both I and II follow",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs010",
        "question": "A, B, C, D and E are sitting on a bench. A is sitting next to B, C is sitting next to D, D is not sitting with E who is on the left end of the bench. C is on the second position from the right. A is to the right of B and E. A and C are sitting together. In which position is A sitting?",
        "options": ["Between B and D", "Between B and C", "Between E and D", "Between C and E"],
        "answer": "Between B and C",
        "difficulty": "Easy",
        "topic": "Number Series",
    },
    {
        "id": "rs011",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q11)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs012",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q12)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs013",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q13)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs014",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q14)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs015",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q15)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs016",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q16)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs017",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q17)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs018",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q18)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Easy",
        "topic": "Blood Relations",
    },
    {
        "id": "rs019",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q19)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Medium",
        "topic": "Blood Relations",
    },
    {
        "id": "rs020",
        "question": "Which term completes the series: A3, C5, E9, G17, ? (Q20)",
        "options": ["I33", "I30", "H33", "J35"],
        "answer": "I33",
        "difficulty": "Medium",
        "topic": "Blood Relations",
    },
    {
        "id": "rs021",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q21)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs022",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q22)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs023",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q23)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs024",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q24)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs025",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q25)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs026",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q26)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs027",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q27)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs028",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q28)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs029",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q29)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs030",
        "question": "Syllogism: Statements: Some cats are dogs. No dog is toy. Conclusions: I. Some cats are not toys. II. Some toys are cats. (Q30)",
        "options": ["Only I follows", "Only II follows", "Both follow", "Neither follows"],
        "answer": "Only I follows",
        "difficulty": "Medium",
        "topic": "Syllogisms",
    },
    {
        "id": "rs031",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q31)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Medium",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs032",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q32)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Medium",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs033",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q33)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Medium",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs034",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q34)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Medium",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs035",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q35)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Medium",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs036",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q36)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Medium",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs037",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q37)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Hard",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs038",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q38)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Hard",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs039",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q39)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Hard",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs040",
        "question": "If 'APPLE' is coded as '5' and 'BANANA' is coded as '6', what is code of 'PREDICTOR' (Q40)?",
        "options": ["7", "8", "9", "10"],
        "answer": "9",
        "difficulty": "Hard",
        "topic": "Coding-Decoding",
    },
    {
        "id": "rs041",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q41)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs042",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q42)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs043",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q43)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs044",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q44)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs045",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q45)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs046",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q46)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs047",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q47)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs048",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q48)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs049",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q49)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs050",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q50)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
    {
        "id": "rs051",
        "question": "Reasoning puzzle: A is taller than B but shorter than C. D is taller than E but shorter than B. Who is the tallest (Q51)?",
        "options": ["A", "B", "C", "D"],
        "answer": "C",
        "difficulty": "Hard",
        "topic": "Puzzles",
    },
]
